### ISSUE TITLE
Localization: wrap strings

### ISSUE THREAD

**Issue by jpetto** [mozilla/kitsune#3325]
Some strings are not wrapped. See [original comment](https://github.com/mozilla/kitsune/pull/3312#issuecomment-422430593) with examples.

**Comment by jpetto** [comment]
Hm, _most_ of the strings mentioned in the original comment do appear to be wrapped for translation, but _are_ new strings.

- [Find help...](https://github.com/mozilla/kitsune/pull/3312/files#diff-9f80997acbc5d299808f999b9f3c8e7dR9)
- [Help articles](https://github.com/mozilla/kitsune/pull/3312/files#diff-2acaaa594db84287602d1993a32ca26cR11)
- [Get community support](https://github.com/mozilla/kitsune/pull/3312/files#diff-9f80997acbc5d299808f999b9f3c8e7dR22)
- [Volunteer](https://github.com/mozilla/kitsune/pull/3312/files#diff-0b59efd85b03f4611418629761f2cae0R196)
- [Search and navigate easily with these essential features](https://github.com/mozilla/kitsune/pull/3312/files#diff-9fb8e903b164ade55bd42033512b9b29R81)

I will be filing a PR to wrap the following strings:
- These fine people helped write this article:
- You can help too - find out how

I'm not familiar with the localization process on kitsune - will these new strings block launching? If so, what's our plan?

cc @madasan @vesper-mozilla

**Comment by vesper-mozilla** [comment]
@jpetto for localization, we have the following documentation explaining how it's done on Kitsune: https://kitsune.readthedocs.io/en/latest/localization.html - I hope this helps.

**Comment by jpetto** [comment]
@vesper-mozilla I believe all new strings are wrapped according to the docs. Does anything else need to be done here?

**Comment by vesper-mozilla** [comment]
> 
> 
> @vesper-mozilla I believe all new strings are wrapped according to the docs. Does anything else need to be done here?

LGTM, thank you!

**Comment by vesper-mozilla** [comment]
Hi @jpetto. Looks like it did not work as expected. I do not know why that would happen, since your PR should have done the trick.

The strings are live, but Pontoon is still not showing them as localizable: for example https://pontoon.mozilla.org/pl/sumo/all-resources/?search=Find+help or https://pontoon.mozilla.org/pl/sumo/all-resources/?search=Volunteer

OTOH, some strings for the redesign have been localized but have not been picked up by the live site, for example https://pontoon.mozilla.org/pl/sumo/all-resources/?search=You+can+help+too+-+find+out+how&string=150554

**Comment by pmac** [comment]
Oh that's probably my fault. I need to do another extract and merge to get the new strings into the l10n repo. I'll do that today.

**Comment by pmac** [comment]
I have updated strings in github, and have pulled in new translations. An updated build is live on stage now that I think improves things. I'll be pushing it to prod shortly.

**Comment by pmac** [comment]
I've deployed the string updates to prod. More will be coming in during the next several days. I'll try to update the site often to fix more of this issue as we can.

**Comment by jpetto** [comment]
Just making sure we're good code-wise on this issue. @vesper-mozilla - any code changes needed, or did @pmac's work take care of the issue?

**Comment by vesper-mozilla** [comment]
Thanks for working on this, @pmac and @jpetto - I understand the site will be getting updated gradually? We can still see stuff in English for Spanish, for example - https://support.mozilla.org/es/

Cheers!

**Comment by nukeador** [comment]
Same here, still a lot of English strings in the Spanish site.

**Comment by nukeador** [comment]
![imagen](https://user-images.githubusercontent.com/531906/46752237-fddf7c00-ccbc-11e8-995b-5b58dca73794.png)

**Comment by vesper-mozilla** [comment]
Thank you for reporting, @nukeador!
@pmac @jpetto - looks like those strings ("Found X results...", "We couldn't find any results for QUERY in LANG. Maybe one of these articles will be helpful?") are already in Pontoon (and approved) - just not getting pulled into the site for some reason. Probably another update will fix this issue?

Thank you for staying on top of this, everyone. I really appreciate it!
