### ISSUE TITLE
[FxA] mobile: The arrows from the user menu are wrongly displayed on RTL language

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3749]
[Environment]:
Firefox for Android

[STR]:
1.Log in https://support-dev.allizom.org
2.Set RTL language ( e.g. AR)
3.Open the user menu

[Actual result]:
The arrows for Contributor tools and for My profile are not correctly displayed

![Screenshot_20190625-120910](https://user-images.githubusercontent.com/41474886/60086659-2e305300-9744-11e9-982a-320c9f513d56.png)

@kkellydesign

**Comment by kkellydesign** [comment]
This is in: 
https://github.com/mozilla/kitsune/pull/3756
https://github.com/mozilla/kitsune/commit/e7487546359e16e38de322993ed2d5420ab11bf4

<img width="593" alt="Screen Shot 2019-06-25 at 2 51 35 PM" src="https://user-images.githubusercontent.com/202590/60124986-d2bc9000-9758-11e9-9f4f-755e490c1315.png">

**Comment by rleitan** [comment]
![2019-06-26_15h38_30](https://user-images.githubusercontent.com/41474886/60180330-76c13c80-9828-11e9-9a6b-eac2c1be2b73.png)

@kkellydesign, can you please add a space between My profile and the arrow?

**Comment by kkellydesign** [comment]
This is fixed, in https://github.com/mozilla/kitsune/pull/3764

<img width="236" alt="Screen Shot 2019-06-26 at 1 02 58 PM" src="https://user-images.githubusercontent.com/202590/60200044-46bb6e80-9813-11e9-8365-8c6ce77dac21.png">

**Comment by rleitan** [comment]
I can still reproduce the issue with the arrow with AR locale

@kase

**Comment by kkellydesign** [comment]
@rleitan Can you please post a URL? 

@akatsoulas, can you confirm that the latest PR has been deployed?

**Comment by akatsoulas** [comment]
@kkellydesign that was a false alarm. The issue has been marked as ready to deploy. Probably I moved the issue into the QA column sooner that it reached the dev server.
